config/routes.rb
SEProject::Application.routes.draw do
  root :to => 'home#index', :as => 'home'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get    'logout'  => 'sessions#destroy'
  post  '/sort' =>  'home#sort', :as => :sort_emergencies

  resources :emergencies
  get 'emergency/:id/donors' => 'inference#emergency_donors', :as => :emergency_donors
  get 'donors' => 'inference#donors', :as => :donors
  get 'donors/:id' => 'inference#donor_emergencies', :as => :donor_emergencies
  post 'pledge' => 'pledge#create', :as => :pledge
  get 'pledge/:id' => 'pledge#new', :as => :new_pledge

end

app/models/donation.rb
class Donation < ActiveRecord::Base
  attr_accessible :user, :emergency, :amount_donated
  belongs_to :user
  belongs_to :emergency
end

app/models/emergency.rb
class Emergency < ActiveRecord::Base
  attr_accessible :amount_needed, :emergency_type, :lat, :long, :start_time, :end_time
  has_many :donations
  has_many :users, through: :donations
  after_initialize :init

    def init
      self.end_time ||= 2020-10-10
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password, :user_type #type can be either fieldworker,donor,ngo-worker
  has_many :donations
  has_many :emergencies, through: :donations

  def authenticate(pass)
  	password == pass
  end

  def self.getUsersByType(type)
  	User.where('user_type = ?', type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
 before_filter :set_user
 
 def set_user
    unless request.path == "/login"
      @current_user ||= session[:current_user];
      redirect_to '/login' unless @current_user;
    end
 end

 def location
  if params[:location].blank?
    if Rails.env.test? || Rails.env.development?
      @location ||= Geocoder.search(ENV['RAILS_TEST_IP_ADDRESS']).first
      @location ||= Geocoder.search('2.3.4.5').first
    else
      @location ||= request.location
    end
  else
    params[:location].each {|l| l = l.to_i } if params[:location].is_a? Array
    @location ||= Geocoder.search(params[:location]).first
    @location
  end
end

end

app/controllers/emergencies_controller.rb
require 'date'
class EmergenciesController < ApplicationController

	def index
		@emergencies = Emergency.all()
		render :json => @emergencies
	end
	def new
		@current_time = Time.now.strftime("%d/%m/%Y %H:%M")
		location
	end

	def create
		@emergency = Emergency.create!(params[:emergency])
		flash[:info] = 'New Emergency added.'
		redirect_to home_path
	end

	def show
		id = params[:id]
		@emergency = Emergency.find(id)
		@user = session[:current_user];
		#redirect_to emergency_path(@emergency)
	end

	def pledge
		@emergency = Emergency.find(params[:id]);
		@user = session[:current_user];
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@user = session[:current_user];
	end
	def sort
		sort = params[:sort_by]
		if (sort == 'Amount needed')
			flash[:notice] = 'Areas coded by amount needed'
		elsif (sort == 'Number of Emergencies')
			flash[:notice] = 'Areas coded by number of emergencies'
		end
		redirect_to home_path
	end
end

app/controllers/inference_controller.rb
class InferenceController < ApplicationController

  def donors
    @donors = User.getUsersByType('donor')
    render 'donors'
  end

  def donor_emergencies
   @emergencies = User.where('id = ?',params[:id]).first.emergencies
   render 'emergenices'
  end

  def emergency_donors
    @donors = Emergency.where('id = ?',params[:id]).first.users
    render 'donors'
  end

end

app/controllers/pledge_controller.rb
class PledgeController < ApplicationController
	def create
		h = params[:donation];
		@emergency = Emergency.find(h[:emergency_id]);
		@user = User.find(h[:user_id]);
		Donation.create!({:user=>@user,:emergency=>@emergency,:amount_donated=>h[:amount_donated]});
		flash[:info] = "Amount PKR #{h[:amount_donated]} pledged to emergency #{h[:emergency_id]}"
		redirect_to home_path
	end

	def new
		@emergency = Emergency.find(params[:id]);
		@user = session[:current_user];
		render 'new_pledge'
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	logged_in = false
  	user = User.find_by_username(params[:session][:username])
  	if user
  		if user.authenticate(params[:session][:password])
	  		flash.now[:success] = "Logged in :)"
			log_in(user)
			logged_in = true
		else
			flash.now[:danger] = "Wrong password >_<"
		end
  	else
  		flash.now[:danger] = "Sorry I don't know you o.0"
  	end

  	if logged_in
  		redirect_to home_path
  	else
  		render 'new'
  	end
  end

  def destroy
  	log_out
  	render 'new'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
    	session[:current_user] = user
  	end

  	def log_out
    	session.delete(:current_user)
  	end

  	def current_user
  		session[:current_user]
  	end
end

app/views/emergencies/new.html.haml
-# in app/views/emergencies/add.html.haml

.col-md-12
	.page-header
		%h1 Add New Emergency

	= form_tag emergencies_path do
		.form-group
			= label :emergency, :emergency_type, 'Type'
			= text_field :emergency, :emergency_type, :class => 'form-control'

		.form-group
			= label :emergency, :amount_needed, 'Amount Needed (PKR)'
			= number_field :emergency, :amount_needed, :value => 12, :class => 'form-control'

		.form-group
			= label :emergency, :lat, 'Latitude'
			= number_field :emergency, :lat, :value => @location.latitude, :readonly => true, :class => 'form-control'

		.form-group
			= label :emergency, :long, 'Longitude'
			= number_field :emergency, :long, :value => @location.longitude, :readonly => true, :class => 'form-control'

		.form-group
			= label :emergency, :start_time, 'Emergency Date'
			= text_field :emergency, :start_time, :value => @current_time, :readonly =>true, :class => 'form-control'

		= submit_tag 'Add Emergency', :class => 'btn btn-success'

		= hidden_field :emergency, :end_time, :value => '2020-10-10'

	= link_to 'Back to Home Page', home_path, :class => 'back-link'

app/views/emergencies/show.html.haml
-# in app/views/movies/show.html.haml

.col-md-12
  .page-header
    %h2 Details about Emergency

  %ul#details.list-group
    %li.list-group-item
      Emergency Location-latitude:
      = @emergency.lat
    %li.list-group-item
      Emergency Location-longitude:
      = @emergency.long
    %li.list-group-item
      Emergency Type:
      = @emergency.emergency_type
    %li.list-group-item
      Added on:
      = @emergency.start_time
    %li.list-group-item
      Amount needed:
      = @emergency.amount_needed

  -if @user.user_type == 'NGO-worker'
    = button_to 'See Donors', emergency_donors_path(@emergency.id), :method => :get, :class => 'btn btn-default'
  -elsif @user.user_type == 'donor'
    = button_to 'Pledge', new_pledge_path(@emergency.id), :method => :get, :class => 'btn btn-default'
  //= link_to 'Edit', edit_emergecny_path(@emergency)
  //= button_to 'Pledge', pledge_path
  = button_to 'Delete', emergencies_path(@emergency), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-danger'

  = link_to 'Back to Home Page', home_path, :class => 'back-link'

app/views/home/index.html.erb
<% provide(:title, "Welcome") %>
<% if @user.user_type == 'field-worker' %>
	<%= link_to 'Add Emergency', new_emergency_path, {:class => 'col-md-12 btn btn-success' }%>
	<%= form_tag(emergencies_path, {:method => :get}) do %>
  		<%= label_tag 'Options for sorting: ' %>
  		<%= select_tag :sort_by, options_for_select(['Amount needed', 'Number of Emergencies']) %>
  		<%= submit_tag 'Sort By' %>
  	<% end %>	
<% end %>
<% if @user.user_type == 'NGO-worker' %>
	<%= link_to 'View All Donors', donors_path, {:class => 'col-md-12 btn btn-success'} %>
<% end %>

app/views/home/index.html.haml
- provide(:title, "Welcome")
.map-holder.col-xs-8
	%input.form-control.map-control{:name => 'map-input'}
	.map-canvas
.controls-holder.col-xs-4
	= form_tag(sort_emergencies_path, {:method => :post}) do
		.form-group
			= label_tag 'Options for sorting: '
			= select_tag :sort_by, options_for_select(['Amount needed', 'Number of Emergencies']), {:class => 'form-control'}
		= submit_tag 'Sort By', {:class => 'btn btn-default'}
- if current_user && current_user.user_type == 'field-worker'
	= link_to 'Add Emergency', new_emergency_path, {:class => 'btn btn-success hero-btn' }
- elsif current_user && current_user.user_type == 'NGO-worker'
	= link_to 'View All Donors', donors_path, {:class => 'col-md-12 btn btn-success'}

app/views/inference/donors.html.haml
%table
  %tbody
    - @donors.each do |donor|
      %tr
        %td= link_to donor.username, donor_emergencies_path(donor.id)

app/views/inference/emergenices.html.haml
- if(@emergencies.length > 0)
  %table
    %tbody
      %tr
        %td= 'id'
        %td= 'type'
        %td= 'amount needed'
        %td= 'start time'
        %td= 'end time'
      - @emergencies.each do |emergency|
        %tr
          %td= "Emergency #{emergency.id}"
          %td= emergency.emergency_type
          %td= emergency.amount_needed
          %td= emergency.start_time
          %td= emergency.end_time

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SEProject :: <%= yield :title %> </title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<a class="navbar-brand" href="#">
			    <span class="glyphicon glyphicon-map-marker"></span>
			</a>
		</div>
		<% if current_user %>
			<ul class="nav navbar-nav navbar-right">
		        <li class="dropdown">
		          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><strong><%= current_user.username %></strong> who is a <%= current_user.user_type %> <span class="caret"></span></a>
		          <ul class="dropdown-menu" role="menu">
		            <li><%= link_to 'Logout', logout_path %></li>
		          </ul>
		        </li>
		    </ul>
		<% end %>
	</div>
	</nav>

	<div class="container-fluid">
		<div class = "alerts-container">
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %> alert-dismissible" role="alert">
				  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				  <%= value %>
				</div>
		  	<% end %>
		</div>
	  <%= yield %>
	</div>

	<script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?libraries=places,visualization&key=AIzaSyD3Jn-bBrowY1713IpqVkuOi7XToPeMakY"></script>

	<%= javascript_include_tag "application" %>
</body>
</html>

app/views/pledge/new_pledge.html.haml
.col-md-12
	.page-header
		%h1 Pledge Money
		= form_tag pledge_path do
			.form-group
				= label :donation, :emergency_id, 'ID'
				= text_field :donation, :emergency_id, :value => @emergency.id, :readonly => true
			.form-group
				= label :emergency, :emergency_type, 'Type'
				= text_field :emergency, :emergency_type, :value => @emergency.emergency_type, :readonly => true
			.form-group
				= label :donation, :amount_donated, 'Enter Amount (PKR)'
				= number_field :donation, :amount_donated, :value => 0
			.form-group
				= hidden_field :donation,:user_id, :value => @user.id

			= submit_tag 'Submit Pledge', :class => 'btn btn-success'